vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        offre_pdf:
            uri_prefix: /pdf/offres
            upload_destination: '%kernel.project_dir%/public/pdf/offres'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
